# Generated by Django 4.2.23 on 2026-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=50)),
                ('design', models.CharField(max_length=20)),
                ('age_range', models.CharField(max_length=20)),
                ('movie_frequency', models.CharField(max_length=20)),
                ('pairwise_observations', models.JSONField(default=list)),
                ('ranking_observations', models.JSONField(default=list)),
                ('elapsed_seconds', models.FloatField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
